# Generated by Django 5.2.12 on 2026-03-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('numeric_id', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cached_episodes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'anime',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('order', models.IntegerField(default=0)),
                ('episode_url', models.URLField(max_length=1000)),
                ('data_number', models.CharField(blank=True, max_length=64)),
                ('ep_query', models.CharField(blank=True, max_length=64)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.anime')),
            ],
            options={
                'db_table': 'episode',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(db_index=True, max_length=1000, unique=True)),
                ('source_type', models.CharField(choices=[('rapid-cloud', 'rapid-cloud'), ('other', 'other')], default='other', max_length=32)),
                ('response_status', models.IntegerField(default=0)),
                ('response_data', models.JSONField(default=dict)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='anime.episode')),
            ],
            options={
                'db_table': 'episode_source',
            },
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['anime', 'order'], name='episode_anime_i_d3d7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='episodesource',
            index=models.Index(fields=['episode', 'source_type'], name='episode_sou_episode_ab502d_idx'),
        ),
    ]
